# Generated by Django 3.1.1 on 2020-09-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostdoc', '0002_auto_20200922_2236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docupload',
            old_name='user',
            new_name='uploaded_by',
        ),
        migrations.AddField(
            model_name='docupload',
            name='doc_givenname',
            field=models.CharField(default='', max_length=200, verbose_name='Document Givenname'),
        ),
        migrations.AddField(
            model_name='docupload',
            name='doc_surname',
            field=models.CharField(default='', max_length=200, verbose_name='Document Surname'),
        ),
    ]
