# Generated by Django 3.1.1 on 2020-10-19 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lostdoc', '0004_docrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='docrequest',
            name='current_address',
            field=models.CharField(default='Kampala,Bwaise', max_length=100, verbose_name='Where is your current location (e.g.Kampala,Bwaise) ?'),
        ),
        migrations.AddField(
            model_name='docrequest',
            name='urgency',
            field=models.CharField(choices=[('Days', 'Days'), ('Weeks', 'Weeks'), ('Months', 'Months')], default='', max_length=10, verbose_name='How urgent do you need the document ?'),
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('New Document', 'New Document'), ('Renew Document', 'Renew Document'), ('Others', 'Others')], max_length=50, verbose_name='Type of Service')),
                ('description', models.TextField(verbose_name='Summarize your request here')),
                ('requested_date', models.DateTimeField(auto_now_add=True, verbose_name='Requested Date')),
                ('urgency', models.CharField(max_length=10, verbose_name='How urgent do you need the document ?')),
                ('current_address', models.CharField(max_length=100, verbose_name='Where is your current location (e.g.Kampala,Bwaise) ?')),
                ('doc_requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('doctype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lostdoc.document', verbose_name='Document Type')),
            ],
        ),
        migrations.CreateModel(
            name='NotFound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_date', models.DateTimeField(auto_now_add=True, verbose_name='Requested Date')),
                ('doc_lost_location', models.CharField(max_length=300, verbose_name='Specify (e.g.Kampala,Bwaise) where you think, you lost the document ?')),
                ('urgency', models.CharField(choices=[('Days', 'Days'), ('Weeks', 'Weeks'), ('Months', 'Months')], default='', max_length=10, verbose_name='How urgent do you need the document ?')),
                ('current_address', models.CharField(max_length=100, verbose_name='Where is your current location (e.g.Kampala,Bwaise) ?')),
                ('doc_requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('doctype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lostdoc.document', verbose_name='Document Type')),
            ],
        ),
    ]
