# Generated by Django 3.1.1 on 2020-10-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostdoc', '0005_auto_20201019_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequest',
            old_name='doc_requester',
            new_name='service_requester',
        ),
        migrations.AlterField(
            model_name='notfound',
            name='current_address',
            field=models.CharField(default='Kampala,Bwaise-Shell', max_length=100, verbose_name='Where is your current location (e.g.Kampala,Bwaise) ?'),
        ),
        migrations.AlterField(
            model_name='notfound',
            name='doc_lost_location',
            field=models.CharField(default='Kampala,Bwaise-Shell', max_length=300, verbose_name='Specify (e.g.Kampala,Bwaise) where you think, you lost the document ?'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='current_address',
            field=models.CharField(default='Kampala,Bwaise-Shell', max_length=100, verbose_name='Where is your current location (e.g.Kampala,Bwaise) ?'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='urgency',
            field=models.CharField(choices=[('Days', 'Days'), ('Weeks', 'Weeks'), ('Months', 'Months')], default='', max_length=10, verbose_name='How urgent do you need the document ?'),
        ),
    ]
