# Generated by Django 3.1.1 on 2020-10-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostdoc', '0009_document_docimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='docupload',
            name='docfile_two',
            field=models.ImageField(default='', upload_to='documents/', verbose_name='Back Image'),
        ),
        migrations.AlterField(
            model_name='docupload',
            name='docfile',
            field=models.ImageField(upload_to='documents/', verbose_name='Front Image'),
        ),
    ]
