# Generated by Django 3.1.1 on 2020-10-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostdoc', '0010_auto_20201028_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docupload',
            name='docfile',
            field=models.ImageField(default='', upload_to='documents/', verbose_name='Front Image'),
        ),
    ]
